# Generated by Django 6.0.5 on 2026-06-07 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_odemedonemi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BirikimHedefi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finans_turu', models.CharField(choices=[('kisisel', 'Kişisel Finans'), ('ev', 'Ev Finans'), ('isyeri', 'İşyeri Finans')], default='kisisel', max_length=20)),
                ('hedef_adi', models.CharField(max_length=120)),
                ('hedef_tutar', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mevcut_tutar', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('aylik_katki', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('hedef_tarihi', models.DateField(blank=True, null=True)),
                ('aktif', models.BooleanField(default=True)),
                ('aciklama', models.TextField(blank=True)),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KategoriButcesi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finans_turu', models.CharField(choices=[('kisisel', 'Kişisel Finans'), ('ev', 'Ev Finans'), ('isyeri', 'İşyeri Finans')], default='kisisel', max_length=20)),
                ('yil', models.PositiveIntegerField()),
                ('ay', models.PositiveSmallIntegerField()),
                ('hedef_tutar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.kategori')),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('kullanici', 'finans_turu', 'kategori', 'yil', 'ay')},
            },
        ),
    ]
