# Generated by Django 6.0.5 on 2026-06-08 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


ESKI_FINANS_ALANI_ADLARI = {
    'kisisel': ('Kişisel Finans', '#2563eb', 'wallet2'),
    'ev': ('Ev Finansı', '#16a34a', 'house'),
    'isyeri': ('İşletme Finansı', '#7c3aed', 'briefcase'),
}


def eski_finans_turlerini_tasi(apps, schema_editor):
    FinansAlani = apps.get_model('core', 'FinansAlani')
    user_app, user_model = settings.AUTH_USER_MODEL.split('.')
    Kullanici = apps.get_model(user_app, user_model)
    model_adlari = [
        'Gelir',
        'Gider',
        'ButceHedefi',
        'KategoriButcesi',
        'BirikimHedefi',
        'Kategori',
        'TekrarlayanOdeme',
    ]
    modeller = [apps.get_model('core', model_adi) for model_adi in model_adlari]

    for kullanici in Kullanici.objects.all():
        FinansAlani.objects.get_or_create(
            kullanici_id=kullanici.id,
            ad='Kişisel Finans',
            defaults={
                'aciklama': 'Varsayılan finans alanı',
                'renk': '#2563eb',
                'ikon': 'wallet2',
            },
        )

    kullanici_finans_turleri = set()
    for model in modeller:
        for kullanici_id, finans_turu in model.objects.exclude(kullanici_id=None).values_list('kullanici_id', 'finans_turu').distinct():
            kullanici_finans_turleri.add((kullanici_id, finans_turu or 'kisisel'))

    for kullanici_id, finans_turu in kullanici_finans_turleri:
        ad, renk, ikon = ESKI_FINANS_ALANI_ADLARI.get(
            finans_turu,
            (str(finans_turu).title(), '#2563eb', 'wallet2'),
        )
        alan, _ = FinansAlani.objects.get_or_create(
            kullanici_id=kullanici_id,
            ad=ad,
            defaults={
                'aciklama': f'Eski {finans_turu} finans türünden taşındı.',
                'renk': renk,
                'ikon': ikon,
            },
        )
        for model in modeller:
            model.objects.filter(kullanici_id=kullanici_id, finans_turu=finans_turu).update(
                finans_alani_id=alan.id,
                finans_turu=str(alan.id),
            )


def geri_al(apps, schema_editor):
    # Geri alma durumunda FK bağlantısını temizlemek yeterli; eski metinsel
    # değerler veri kaybı olmadan otomatik tahmin edilemez.
    for model_adi in ['Gelir', 'Gider', 'ButceHedefi', 'KategoriButcesi', 'BirikimHedefi', 'Kategori', 'TekrarlayanOdeme']:
        model = apps.get_model('core', model_adi)
        model.objects.update(finans_alani_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_birikimhedefi_kategoributcesi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='birikimhedefi',
            name='finans_turu',
            field=models.CharField(default='kisisel', max_length=64),
        ),
        migrations.AlterField(
            model_name='butcehedefi',
            name='finans_turu',
            field=models.CharField(default='kisisel', max_length=64),
        ),
        migrations.AlterField(
            model_name='gelir',
            name='finans_turu',
            field=models.CharField(default='kisisel', max_length=64),
        ),
        migrations.AlterField(
            model_name='gider',
            name='finans_turu',
            field=models.CharField(default='kisisel', max_length=64),
        ),
        migrations.AlterField(
            model_name='kategori',
            name='finans_turu',
            field=models.CharField(default='kisisel', max_length=64),
        ),
        migrations.AlterField(
            model_name='kategoributcesi',
            name='finans_turu',
            field=models.CharField(default='kisisel', max_length=64),
        ),
        migrations.AlterField(
            model_name='tekrarlayanodeme',
            name='finans_turu',
            field=models.CharField(default='kisisel', max_length=64),
        ),
        migrations.CreateModel(
            name='FinansAlani',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100)),
                ('aciklama', models.TextField(blank=True)),
                ('renk', models.CharField(default='#2563eb', max_length=20)),
                ('ikon', models.CharField(default='wallet2', max_length=50)),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('ad',),
                'unique_together': {('kullanici', 'ad')},
            },
        ),
        migrations.AddField(
            model_name='birikimhedefi',
            name='finans_alani',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.finansalani'),
        ),
        migrations.AddField(
            model_name='butcehedefi',
            name='finans_alani',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.finansalani'),
        ),
        migrations.AddField(
            model_name='gelir',
            name='finans_alani',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.finansalani'),
        ),
        migrations.AddField(
            model_name='gider',
            name='finans_alani',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.finansalani'),
        ),
        migrations.AddField(
            model_name='kategori',
            name='finans_alani',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.finansalani'),
        ),
        migrations.AddField(
            model_name='kategoributcesi',
            name='finans_alani',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.finansalani'),
        ),
        migrations.AddField(
            model_name='tekrarlayanodeme',
            name='finans_alani',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.finansalani'),
        ),
        migrations.RunPython(eski_finans_turlerini_tasi, geri_al),
    ]
